# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.pta.gov.pk/")
    self.driver.set_window_size(697, 728)
    self.driver.execute_script("window.scrollTo(0,7410.90869140625)")
    self.driver.execute_script("window.scrollTo(0,11082.7265625)")
    self.driver.execute_script("window.scrollTo(0,12092.7265625)")
    self.driver.execute_script("window.scrollTo(0,6904.54541015625)")
    self.driver.execute_script("window.scrollTo(0,1459.0908203125)")
    self.driver.find_element(By.CSS_SELECTOR, ".mt-8 > .transition-colors").click()
    self.driver.find_element(By.LINK_TEXT, "Numbering").click()
  
