name: PTA Scraper
on:
  push:
    branches: [main]
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Libraries install
        run: pip install selenium pytest webdriver-manager allure-pytest
        
      - name: Run tests
        run: pytest PTA_test1.py -v -s --alluredir=allure-results
        
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results
